# Generated by Django 6.1.1 on 2026-10-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={},
        ),
        migrations.RenameField(
            model_name='contato',
            old_name='data_criacao',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='contato',
            old_name='nome',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='telefone',
        ),
    ]
